# If you change the DB name here, also change it in djangocon2015/settings/travis.py
before_script:
  - psql -c 'create database djangocon2015;' -U postgres
language: python
python:
  - "2.7"
env:
  - TOXENV=djangocon2015
install:
  - pip install -q tox==1.6.1
script:
  - tox -- --settings=djangocon2015.settings.travis
